#!/bin/bash
set -e

# Make sure only root can run this script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi


# Check dependencies
requiredAptDependencies=( "cec-utils" )
missingAptDependencies=()

echo "Checking apt dependencies..."
for elem in "${requiredAptDependencies[@]}"
do
	dpkg -s $elem &> /dev/null
	if [ $? -ne 0 ]
	then
		missingAptDependencies=("${missingAptDependencies[@]}" "$elem")
	fi
done

if [ ${#missingAptDependencies[@]} -gt 0 ]
then
	# printf "Please install missing apt packages via\n"
	# printf "\t'sudo apt install"
	for elem in "${missingAptDependencies[@]}"
	do
		printf "trying to install $elem\n"
		apt -y -q install $elem
		# printf " $elem"
	done
	printf "'\n"
else
	echo "All apt dependencies are met"
fi
echo ""

echo "Checking pip dependencies..."
requiredPipDependencies=( "requests" "cec" "yaml" )
missingPipDependencies=()

for elem in "${requiredPipDependencies[@]}"
do
	python3 -c "import $elem" &> /dev/null
	if [ $? -ne 0 ]
	then
    if [ "$elem" = "yaml" ]
    then
      missingPipDependencies=("${missingPipDependencies[@]}" "pyyaml")
    else
      missingPipDependencies=("${missingPipDependencies[@]}" "$elem")
    fi
	fi
done

if [ ${#missingPipDependencies[@]} -gt 0 ]
then
	# printf "Please install missing pip packages via\n"
	# printf "\t'pip3 install --system"
	for elem in "${missingPipDependencies[@]}"
	do
		# printf " $elem"
		printf "Insalling $elem\n"
		pip3 install --system $elem
	done
	# printf "'\n"
  printf "\n"
  printf "Note that a user has to be in the group 'staff' to install Python packages globally.\n"
  printf "To add a user to the 'staff' group execute 'sudo adduser <username> staff'.\n"
else
	echo "All pip dependencies are met"
fi
echo ""

# if [ ${#missingAptDependencies[@]} -gt 0 ] || [ ${#missingPipDependencies[@]} -gt 0 ]
# then
# 	exit 1
# fi


# Starting installation
echo "Starting installation..."
echo "Setting up systemd service..."
sed -i "s|WorkingDirectory=.*|WorkingDirectory=$(pwd)|g" alarmmonitor.service \
&& ln -s "$(pwd)"/alarmmonitor.service /etc/systemd/system/alarmmonitor.service \
&& systemctl enable alarmmonitor \
&& systemctl start alarmmonitor
echo ""


if [ $? -ne 0 ]; then
    echo "Errors occured during installation" > /dev/stderr
    exit 1
fi
echo "Installation successful"
