#!/bin/bash

# Make sure only root can run this script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi


# Starting deinstallation
echo "Starting deinstallation..."
systemctl stop alarmmonitor \
&& systemctl disable alarmmonitor \
&& rm /etc/systemd/system/alarmmonitor.service
echo ""


if [ $? -ne 0 ]; then
    echo "Errors occured during deinstallation" > /dev/stderr
    exit 1
fi
echo "Deinstallation successful"
